name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Deploy to Google Cloud
      run: |
        gcloud compute instances update-container ${{ secrets.INSTANCE_NAME }} \
          --zone ${{ secrets.INSTANCE_ZONE }} \
          --container-image ${{ secrets.REPO_PATH }}
