name: Deploy to Google Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest


    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/otp-checker:latest

    - id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"
      
    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet

    - name: Pull and push to Google Artifact Registry
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/otp-checker:latest
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/otp-checker:latest ${{secrets.REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT}}/${{secrets.REPO_NAME}}/otp-checker:latest
        docker push ${{secrets.REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT}}/${{secrets.REPO_NAME}}/otp-checker:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy ${{secrets.GCP_PROJECT}} --image ${{secrets.REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT}}/${{secrets.REPO_NAME}}/otp-checker:latest --region ${{secrets.REGION}} --platform managed --allow-unauthenticated